sonar.organization=rof20004
sonar.projectKey=rof20004_tech-challenge-domains

sonar.sources=./application
sonar.exclusions=**/*_test.go

sonar.tests=./tests/unit
sonar.test.inclusions=**/*_test.go

sonar.go.coverage.reportPaths=./coverage.out
