name: 1-Quality

on:
  push:
    branches:
      - dev

jobs:
  quality:
    name: Sonar Test & Coverage
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Tests
        run:
          ./tests/unit/_run.sh

      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@v2.3.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
