name: 1-Quality

on:
  push:
    branches:
      - dev

jobs:
  test:
    name: Testes unitários
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Tests
        run:
          ./tests/unit/_run.sh

      - name: Upload coverage file
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: ./coverage.out

  quality:
    name: Sonar Scan
    runs-on: ubuntu-latest
    environment: dev
    needs: test

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          
      - name: Download test results
        uses: actions/download-artifact@v3
        with:
          name: test-results
          path: ./coverage.out

      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@v2.3.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
